"""Add spells and active_spells tables

Revision ID: 59f9e9c0b8d0
Revises: 3fb7b655c2e0
Create Date: 2024-08-06 11:32:48.581688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f9e9c0b8d0'
down_revision: Union[str, None] = '3fb7b655c2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
