"""add spells table

Revision ID: aa9973721491
Revises: 59f9e9c0b8d0
Create Date: 2024-08-06 11:47:44.945202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9973721491'
down_revision: Union[str, None] = '59f9e9c0b8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_spell')
    op.drop_column('spell', 'description')
    op.drop_column('spell', 'effect')
    op.drop_column('spell', 'piece_compatibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('piece_compatibility', sa.VARCHAR(length=80), nullable=False))
    op.add_column('spell', sa.Column('effect', sa.VARCHAR(length=200), nullable=False))
    op.add_column('spell', sa.Column('description', sa.VARCHAR(length=200), nullable=False))
    op.create_table('active_spell',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('spell_id', sa.INTEGER(), nullable=False),
    sa.Column('turns_left', sa.INTEGER(), nullable=False),
    sa.Column('target_piece', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
